#kafka config
bootstrap-servers: ${bootstrap_servers:localhost:9092}

service:
  mode: ${service_mode:gateway}

#postgres config
postgres:
  url: ${postgres_db_url:jdbc:postgresql://localhost:5432/mock_service}
  user: ${postgres_user:postgres}
  password: ${postgres_password:postgres}
  table:
    consultation-info : ${consultation_info_table:consultation_info}
    provider-system : ${provider_system:provider_system}
    patient-information : ${patient_information:patient_information}
    beneficiary: ${beneficiary_table:beneficiary_verification}

#hcx base url
hcx_application:
  url: ${hcx_gateway_url:http://dev-hcx.swasth.app}
  api_version: ${version:v0.7}
  token_url: ${auth_url:${hcx_application.url}/auth/realms/swasth-hcx-participants/protocol/openid-connect/token}
  registry_url: ${registry:${hcx_application.url}/api/v0.7/participant/search}
  protocol-base-path: ${protocol_base_path:https://dev-hcx.swasth.app/api/v0.8}

autoresponse: ${auto_response:false}

provider:
  private_key: ${provider_private_key:https://raw.githubusercontent.com/Swasth-Digital-Health-Foundation/hcx-platform/main/hcx-apis/src/test/resources/examples/test-keys/private-key.pem}
  username: ${provider_username:hosp_demoho_82194121@swasth-hcx-dev}
  password: ${provider_password:Opensaber@123}
  participant_code: ${provider_participant_code:hosp_demoho_82194121@swasth-hcx-dev}

aws-url:
  accessKey: ${url_accessKey:}
  accessSecret: ${url_accessSecret:}
  bucketName: ${url_bucketName:}

aws-sns:
  access-key: ${aws_accessKey:}
  access-secret: ${aws_accessSecret:}
  region: ${aws_region:}

phone:
  beneficiary-register : ${phone_beneficiary_register:The OTP for beneficiary app registration is:}
  communication-content: ${phone_communication_content:The OTP for the communication request is:}

otp:
  expiry: ${verification_otp_expiry:300000}